# Generated by Django 5.1.2 on 2024-10-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='coordenadas',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='coordenadas',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
